services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://user:password@db:5432/testdb

  db:
    ports:
      - "5432:5432"
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    volumes:
      - ./test.sql:/docker-entrypoint-initdb.d/test.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d testdb" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always